<?php

use Illuminate\Database\Seeder;

class MunicipiosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Eloquent::unguard();

        $this->createMunicipios();

        Eloquent::reguard();
    }

    private function createMunicipios()
    {
    	$statuses =[

    		['depa_id' =>'4', 'name' => 'Achacachi'],
    		['depa_id' =>'4', 'name' => 'Achocalla'],
    		['depa_id' =>'4', 'name' => 'Alto Beni'],
    		['depa_id' =>'4', 'name' => 'Ancoraimes'],
    		['depa_id' =>'4', 'name' => 'Apolo'],
    		['depa_id' =>'4', 'name' => 'Aucapata'],
    		['depa_id' =>'4', 'name' => 'Ayata'],
    		['depa_id' =>'4', 'name' => 'Ayo Ayo'],
    		['depa_id' =>'4', 'name' => 'Batallas'],
    		['depa_id' =>'4', 'name' => 'Cairoma'],
    		['depa_id' =>'4', 'name' => 'Cajuata'],
    		['depa_id' =>'4', 'name' => 'Calacoto'],
    		['depa_id' =>'4', 'name' => 'Calamarca'],
    		['depa_id' =>'4', 'name' => 'Caquiaviri'],
    		['depa_id' =>'4', 'name' => 'Caranavi'],
    		['depa_id' =>'4', 'name' => 'Catacora'],
    		['depa_id' =>'4', 'name' => 'Charaña'],
    		['depa_id' =>'4', 'name' => 'Chararilla'],
    		['depa_id' =>'4', 'name' => 'Chua Cocani'],
    		['depa_id' =>'4', 'name' => 'Chulumani'],
    		['depa_id' =>'4', 'name' => 'Chuma'],
    		['depa_id' =>'4', 'name' => 'Colquencha'],
    		['depa_id' =>'4', 'name' => 'Colquiri'],
    		['depa_id' =>'4', 'name' => 'Collana'],
    		['depa_id' =>'4', 'name' => 'Combaya'],
    		['depa_id' =>'4', 'name' => 'Comanche'],
    		['depa_id' =>'4', 'name' => 'Copacabana'],
    		['depa_id' =>'4', 'name' => 'Coripata'],
    		['depa_id' =>'4', 'name' => 'Coro Coro'],
    		['depa_id' =>'4', 'name' => 'Coroico'],
    		['depa_id' =>'4', 'name' => 'Curva'],
    		['depa_id' =>'4', 'name' => 'Desaguadero'],
    		['depa_id' =>'4', 'name' => 'El Alto'],
    		['depa_id' =>'4', 'name' => 'Escoma'],
    		['depa_id' =>'4', 'name' => 'Huarina'],
    		['depa_id' =>'4', 'name' => 'Humanata'],
    		['depa_id' =>'4', 'name' => 'Guanay'],
    		['depa_id' =>'4', 'name' => 'Guaqui'],
    		['depa_id' =>'4', 'name' => 'Huatajata'],
    		['depa_id' =>'4', 'name' => 'Ichoca'],
    		['depa_id' =>'4', 'name' => 'Inquisivi'],
    		['depa_id' =>'4', 'name' => 'Irupana'],
    		['depa_id' =>'4', 'name' => 'Ixiamas'],
    		['depa_id' =>'4', 'name' => 'Jesús de Machaca'],
    		['depa_id' =>'4', 'name' => 'Juan.José Pérez'],
    		['depa_id' =>'4', 'name' => 'La Asunta'],
    		['depa_id' =>'4', 'name' => 'La Paz'],
    		['depa_id' =>'4', 'name' => 'Laja'],
    		['depa_id' =>'4', 'name' => 'Licoma Pampa'],
    		['depa_id' =>'4', 'name' => 'Luribay'],
    		['depa_id' =>'4', 'name' => 'Malla'],
    		['depa_id' =>'4', 'name' => 'Mapiri'],
    		['depa_id' =>'4', 'name' => 'Mecapaca'],
    		['depa_id' =>'4', 'name' => 'Mocomoco'],
    		['depa_id' =>'4', 'name' => 'Nazacara de Pacajes'],
    		['depa_id' =>'4', 'name' => 'Palca'],
    		['depa_id' =>'4', 'name' => 'Papel Pampa'],
    		['depa_id' =>'4', 'name' => 'Patacamaya'],
    		['depa_id' =>'4', 'name' => 'Pelechuco'],
    		['depa_id' =>'4', 'name' => 'Palos Blancos'],
    		['depa_id' =>'4', 'name' => 'Pucarani'],
    		['depa_id' =>'4', 'name' => 'Puerto Acosta'],
    		['depa_id' =>'4', 'name' => 'Puerto Carabuco'],
    		['depa_id' =>'4', 'name' => 'Puerto Pérez'],
    		['depa_id' =>'4', 'name' => 'San Buena Ventura'],
    		['depa_id' =>'4', 'name' => 'Santiago de Callapa'],
    		['depa_id' =>'4', 'name' => 'Santiago de Huata'],
    		['depa_id' =>'4', 'name' => 'Santiago de Machaca'],
    		['depa_id' =>'4', 'name' => 'San Andrés de Machaca'],
    		['depa_id' =>'4', 'name' => 'San Pedro de Curahuara'],
    		['depa_id' =>'4', 'name' => 'San Pedro de Tiquina'],
    		['depa_id' =>'4', 'name' => 'Sapahaqui'],
    		['depa_id' =>'4', 'name' => 'Sica Sica'],
    		['depa_id' =>'4', 'name' => 'Sorata'],
    		['depa_id' =>'4', 'name' => 'Quiabaya'],
    		['depa_id' =>'4', 'name' => 'Quime'],
    		['depa_id' =>'4', 'name' => 'Tacacoma'],
    		['depa_id' =>'4', 'name' => 'Taraco'],
    		['depa_id' =>'4', 'name' => 'Teoponte'],
    		['depa_id' =>'4', 'name' => 'Tiawanacu'],
    		['depa_id' =>'4', 'name' => 'Tipuani'],
    		['depa_id' =>'4', 'name' => 'Tito Yupanqui'],
    		['depa_id' =>'4', 'name' => 'Umala'],
    		['depa_id' =>'4', 'name' => 'Viacha'],
    		['depa_id' =>'4', 'name' => 'Waldo Ballivian'],
    		['depa_id' =>'4', 'name' => 'Yaco'],
    		['depa_id' =>'4', 'name' => 'Yanacachi'],
    		['depa_id' =>'2', 'name' => 'Sucre'],
    		['depa_id' =>'2', 'name' => 'Yotala'],
    		['depa_id' =>'2', 'name' => 'YoPoromatala'],
    		['depa_id' =>'2', 'name' => 'Azurduy'],
    		['depa_id' =>'2', 'name' => 'Tarvita'],
    		['depa_id' =>'2', 'name' => 'Villa Zudáñez'],
    		['depa_id' =>'2', 'name' => 'Presto'],
    		['depa_id' =>'2', 'name' => 'Villa Mojocoya'],
    		['depa_id' =>'2', 'name' => 'Icla'],
    		['depa_id' =>'2', 'name' => 'Padilla'],
    		['depa_id' =>'2', 'name' => 'Tomina'],
    		['depa_id' =>'2', 'name' => 'Sopachuy'],
    		['depa_id' =>'2', 'name' => 'Villa Alcalá'],
    		['depa_id' =>'2', 'name' => 'El Villar'],
    		['depa_id' =>'2', 'name' => 'Monteagudo'],
    		['depa_id' =>'2', 'name' => 'Huacareta'],
    		['depa_id' =>'2', 'name' => 'Tarabuco'],
    		['depa_id' =>'2', 'name' => 'Yamparáez'],
    		['depa_id' =>'2', 'name' => 'Camargo'],
    		['depa_id' =>'2', 'name' => 'San Lucas'],
    		['depa_id' =>'2', 'name' => 'Incahuasi'],
    		['depa_id' =>'2', 'name' => 'Villa Charcas'],
    		['depa_id' =>'2', 'name' => 'Villa Serrano'],
    		['depa_id' =>'2', 'name' => 'Camataqui'],
    		['depa_id' =>'2', 'name' => 'Culpina'],
    		['depa_id' =>'2', 'name' => 'Las Carreras'],
    		['depa_id' =>'2', 'name' => 'Villa Vaca Guzmán'],
    		['depa_id' =>'2', 'name' => 'Huacaya'],
    		['depa_id' =>'2', 'name' => 'Machareti'],
    		['depa_id' =>'3', 'name' => 'Cochabamba'],
    		['depa_id' =>'3', 'name' => 'Aiquile'],
    		['depa_id' =>'3', 'name' => 'Pasarapa'],
    		['depa_id' =>'3', 'name' => 'Omereque'],
    		['depa_id' =>'3', 'name' => 'Ayopaya'],
    		['depa_id' =>'3', 'name' => 'Morochata'],
    		['depa_id' =>'3', 'name' => 'Tarata'],
    		['depa_id' =>'3', 'name' => 'Anzaldo'],
    		['depa_id' =>'3', 'name' => 'Arbieto'],
    		['depa_id' =>'3', 'name' => 'Sacabamba'],
    		['depa_id' =>'3', 'name' => 'Arani'],
    		['depa_id' =>'3', 'name' => 'Vacas'],
    		['depa_id' =>'3', 'name' => 'Arque'],
    		['depa_id' =>'3', 'name' => 'Tocopaya'],
    		['depa_id' =>'3', 'name' => 'Capinota'],
    		['depa_id' =>'3', 'name' => 'Santivañez'],
    		['depa_id' =>'3', 'name' => 'Sicaya'],
    		['depa_id' =>'3', 'name' => 'Cliza'],
    		['depa_id' =>'3', 'name' => 'Toko'],
    		['depa_id' =>'3', 'name' => 'Tolata'],
    		['depa_id' =>'3', 'name' => 'Quillacollo'],
    		['depa_id' =>'3', 'name' => 'Sipe Sipe'],
    		['depa_id' =>'3', 'name' => 'Tiquipaya'],
    		['depa_id' =>'3', 'name' => 'Vinto'],
    		['depa_id' =>'3', 'name' => 'Colcapirhua'],
    		['depa_id' =>'3', 'name' => 'Sacaba'],
    		['depa_id' =>'3', 'name' => 'Colomi'],
    		['depa_id' =>'3', 'name' => 'Villa Tunari'],
    		['depa_id' =>'3', 'name' => 'Tapacarí'],
    		['depa_id' =>'3', 'name' => 'Totora'],
    		['depa_id' =>'3', 'name' => 'Pojo'],
    		['depa_id' =>'3', 'name' => 'Pocona'],
    		['depa_id' =>'3', 'name' => 'Chimoré'],
    		['depa_id' =>'3', 'name' => 'Puerto Villarroel'],
    		['depa_id' =>'3', 'name' => 'Entre Ríos'],
    		['depa_id' =>'3', 'name' => 'Mizque'],
    		['depa_id' =>'3', 'name' => 'Vila Vila'],
    		['depa_id' =>'3', 'name' => 'Alalay'],
    		['depa_id' =>'3', 'name' => 'Punata'],
    		['depa_id' =>'3', 'name' => 'Villa Rivero'],
    		['depa_id' =>'3', 'name' => 'San Benito'],
    		['depa_id' =>'3', 'name' => 'Tacachi'],
    		['depa_id' =>'3', 'name' => 'Cuchumuela'],
    		['depa_id' =>'3', 'name' => 'Bolivar'],
    		['depa_id' =>'3', 'name' => 'Tiraque'],
    		['depa_id' =>'3', 'name' => 'Cocapata'],
    		['depa_id' =>'3', 'name' => 'Shinaota'],
    		['depa_id' =>'5', 'name' => 'Oruro'],
    		['depa_id' =>'5', 'name' => 'Caracollo'],
    		['depa_id' =>'5', 'name' => 'El Chorro'],
    		['depa_id' =>'5', 'name' => 'Soracachi'],
    		['depa_id' =>'5', 'name' => 'Challapata'],
    		['depa_id' =>'5', 'name' => 'Quillacas'],
    		['depa_id' =>'5', 'name' => 'Coruqe'],
    		['depa_id' =>'5', 'name' => 'Choquecota'],
    		['depa_id' =>'5', 'name' => 'Curaguara de Carangas'],
    		['depa_id' =>'5', 'name' => 'Turco'],
    		['depa_id' =>'5', 'name' => 'Huachacalla'],
    		['depa_id' =>'5', 'name' => 'Escara'],
    		['depa_id' =>'5', 'name' => 'Cruz de Machacamarca'],
    		['depa_id' =>'5', 'name' => 'Yunguyo del Litoral'],
    		['depa_id' =>'5', 'name' => 'Esmeralda'],
    		['depa_id' =>'5', 'name' => 'Poopó'],
    		['depa_id' =>'5', 'name' => 'Pazña'],
    		['depa_id' =>'5', 'name' => 'Antequera'],
    		['depa_id' =>'5', 'name' => 'Huanuni'],
    		['depa_id' =>'5', 'name' => 'Machacamarca'],
    		['depa_id' =>'5', 'name' => 'Salinas de Garci Mendoza'],
    		['depa_id' =>'5', 'name' => 'Pampa Aullagas'],
    		['depa_id' =>'5', 'name' => 'Sabaya'],
    		['depa_id' =>'5', 'name' => 'Coipasa'],
    		['depa_id' =>'5', 'name' => 'Chipaya'],
    		['depa_id' =>'5', 'name' => 'Toledo'],
    		['depa_id' =>'5', 'name' => 'Eucaliptus'],
    		['depa_id' =>'5', 'name' => 'Andamarca'],
    		['depa_id' =>'5', 'name' => 'Belén de Andamarca'],
    		['depa_id' =>'5', 'name' => 'Totora'],
    		['depa_id' =>'5', 'name' => 'Santiago de Huari'],
    		['depa_id' =>'5', 'name' => 'La Rivera'],
    		['depa_id' =>'5', 'name' => 'Todos Santos'],
    		['depa_id' =>'5', 'name' => 'Curahuara de Carangas'],
    		['depa_id' =>'5', 'name' => 'Huayllamarca'],
    		['depa_id' =>'7', 'name' => 'Potosí'],
    		['depa_id' =>'7', 'name' => 'Tinguipaya'],
    		['depa_id' =>'7', 'name' => 'Yocalla'],
    		['depa_id' =>'7', 'name' => 'Urmiri'],
    		['depa_id' =>'7', 'name' => 'Uncía'],
    		['depa_id' =>'7', 'name' => 'Chayanta'],
    		['depa_id' =>'7', 'name' => 'Llallagua'],
    		['depa_id' =>'7', 'name' => 'Betanzos'],
    		['depa_id' =>'7', 'name' => 'Chaquí'],
    		['depa_id' =>'7', 'name' => 'Tacobamba'],
    		['depa_id' =>'7', 'name' => 'Colquechaca'],
    		['depa_id' =>'7', 'name' => 'Ravelo'],
    		['depa_id' =>'7', 'name' => 'Pocoata'],
    		['depa_id' =>'7', 'name' => 'Ocuri'],
    		['depa_id' =>'7', 'name' => 'San Pedro'],
    		['depa_id' =>'7', 'name' => 'Toro Toro'],
    		['depa_id' =>'7', 'name' => 'Cotagaita'],
    		['depa_id' =>'7', 'name' => 'Vitichi'],
    		['depa_id' =>'7', 'name' => 'Sacaca'],
    		['depa_id' =>'7', 'name' => 'Caripuyo'],
    		['depa_id' =>'7', 'name' => 'Tupiza'],
    		['depa_id' =>'7', 'name' => 'Atocha'],
    		['depa_id' =>'7', 'name' => 'Colcha K'],
    		['depa_id' =>'7', 'name' => 'San Pedro de Quemes'],
    		['depa_id' =>'7', 'name' => 'San Pablo de Lípez'],
    		['depa_id' =>'7', 'name' => 'Mojinete'],
    		['depa_id' =>'7', 'name' => 'San Antonio de Esmoruco'],
    		['depa_id' =>'7', 'name' => 'Puna'],
    		['depa_id' =>'7', 'name' => 'Caiza D'],
    		['depa_id' =>'7', 'name' => 'Uyuni'],
    		['depa_id' =>'7', 'name' => 'Tomave'],
    		['depa_id' =>'7', 'name' => 'Porco'],
    		['depa_id' =>'7', 'name' => 'Arampampa'],
    		['depa_id' =>'7', 'name' => 'Acasio'],
    		['depa_id' =>'7', 'name' => 'Llica'],
    		['depa_id' =>'7', 'name' => 'Tahua'],
    		['depa_id' =>'7', 'name' => 'Villazón'],
    		['depa_id' =>'7', 'name' => 'San Agustín'],
    		['depa_id' =>'7', 'name' => 'Ckochas'],
    		['depa_id' =>'7', 'name' => 'Chuquihuta Ayllu Jucumani'],
    		['depa_id' =>'9', 'name' => 'Tarija'],
    		['depa_id' =>'9', 'name' => 'Padcaya'],
    		['depa_id' =>'9', 'name' => 'Bermejo'],
    		['depa_id' =>'9', 'name' => 'Yacuiba'],
    		['depa_id' =>'9', 'name' => 'Caraparí'],
    		['depa_id' =>'9', 'name' => 'Villa Montes'],
    		['depa_id' =>'9', 'name' => 'Uriondo'],
    		['depa_id' =>'9', 'name' => 'Yunchará'],
    		['depa_id' =>'9', 'name' => 'San Lorenzo'],
    		['depa_id' =>'9', 'name' => 'El Puente'],
    		['depa_id' =>'9', 'name' => 'Entre Ríos'],
    		['depa_id' =>'8', 'name' => 'Santa Cruz de la Sierra'],
    		['depa_id' =>'8', 'name' => 'Cotoca'],
    		['depa_id' =>'8', 'name' => 'Ayacucho'],
    		['depa_id' =>'8', 'name' => 'La Guardia'],
    		['depa_id' =>'8', 'name' => 'El Torno'],
    		['depa_id' =>'8', 'name' => 'Warnes'],
    		['depa_id' =>'8', 'name' => 'Okinawa I'],
    		['depa_id' =>'8', 'name' => 'San Ignacio'],
    		['depa_id' =>'8', 'name' => 'San Miguel'],
    		['depa_id' =>'8', 'name' => 'San Rafael de Velasco'],
    		['depa_id' =>'8', 'name' => 'Buena Vista'],
    		['depa_id' =>'8', 'name' => 'San Carlos'],
    		['depa_id' =>'8', 'name' => 'Yapacaní'],
    		['depa_id' =>'8', 'name' => 'San Juan'],
    		['depa_id' =>'8', 'name' => 'San José de Chiquitos'],
    		['depa_id' =>'8', 'name' => 'Pailón'],
    		['depa_id' =>'8', 'name' => 'Roboré'],
    		['depa_id' =>'8', 'name' => 'Portachuelo'],
    		['depa_id' =>'8', 'name' => 'Santa Rosa del Sara'],
    		['depa_id' =>'8', 'name' => 'Colpa Bélgica'],
    		['depa_id' =>'8', 'name' => 'Lagunillas'],
    		['depa_id' =>'8', 'name' => 'Charagua'],
    		['depa_id' =>'8', 'name' => 'Cabezas'],
    		['depa_id' =>'8', 'name' => 'Cuevo'],
    		['depa_id' =>'8', 'name' => 'Gutiérrez'],
    		['depa_id' =>'8', 'name' => 'Camiri'],
    		['depa_id' =>'8', 'name' => 'Boyuibe'],
    		['depa_id' =>'8', 'name' => 'Jesús y Montes Claros de los Caballeros del Vallegrande'],
    		['depa_id' =>'8', 'name' => 'Trigal'],
    		['depa_id' =>'8', 'name' => 'Moro Moro'],
    		['depa_id' =>'8', 'name' => 'Postrer Valle'],
    		['depa_id' =>'8', 'name' => 'Pucará'],
    		['depa_id' =>'8', 'name' => 'Samaipata'],
    		['depa_id' =>'8', 'name' => 'Pampa Grande'],
    		['depa_id' =>'8', 'name' => 'Mairana'],
    		['depa_id' =>'8', 'name' => 'Quirusillas'],
    		['depa_id' =>'8', 'name' => 'Montero'],
    		['depa_id' =>'8', 'name' => 'General Saavedra'],
    		['depa_id' =>'8', 'name' => 'Mineros'],
    		['depa_id' =>'8', 'name' => 'Fernández Alonso'],
    		['depa_id' =>'8', 'name' => 'San Pedro de Buena Vista'],
    		['depa_id' =>'8', 'name' => 'Concepción'],
    		['depa_id' =>'8', 'name' => 'San Javier'],
    		['depa_id' =>'8', 'name' => 'San Ramón'],
    		['depa_id' =>'8', 'name' => 'San Julián'],
    		['depa_id' =>'8', 'name' => 'San Antonio de Lomerío'],
    		['depa_id' =>'8', 'name' => 'Cuatro Cañadas'],
    		['depa_id' =>'8', 'name' => 'San Matías'],
    		['depa_id' =>'8', 'name' => 'Comarapa'],
    		['depa_id' =>'8', 'name' => 'Saipina'],
    		['depa_id' =>'8', 'name' => 'Puerto Suárez'],
    		['depa_id' =>'8', 'name' => 'Puerto Quijarro'],
    		['depa_id' =>'8', 'name' => 'Carmen Rivero Torrez'],
    		['depa_id' =>'8', 'name' => 'Ascensión de Guarayos'],
    		['depa_id' =>'8', 'name' => 'Urubichá'],
    		['depa_id' =>'8', 'name' => 'El Puente'],
    		['depa_id' =>'1', 'name' => 'Trinidad'],
    		['depa_id' =>'1', 'name' => 'San Javier'],
    		['depa_id' =>'1', 'name' => 'Riberalta'],
    		['depa_id' =>'1', 'name' => 'Guayaramerín'],
    		['depa_id' =>'1', 'name' => 'Reyes'],
    		['depa_id' =>'1', 'name' => 'Reyes'],
    		['depa_id' =>'1', 'name' => 'San Borja'],
    		['depa_id' =>'1', 'name' => 'Santa Rosa'],
    		['depa_id' =>'1', 'name' => 'Rurrenabaque'],
    		['depa_id' =>'1', 'name' => 'Santa Ana del Yacuma'],
    		['depa_id' =>'1', 'name' => 'Exaltación'],
    		['depa_id' =>'1', 'name' => 'San Ignacio de Moxos'],
    		['depa_id' =>'1', 'name' => 'Loreto'],
    		['depa_id' =>'1', 'name' => 'San Andrés'],
    		['depa_id' =>'1', 'name' => 'San Joaquín'],
    		['depa_id' =>'1', 'name' => 'San Ramón'],
    		['depa_id' =>'1', 'name' => 'Puerto Siles'],
    		['depa_id' =>'1', 'name' => 'Magdalena'],
    		['depa_id' =>'1', 'name' => 'Baures'],
    		['depa_id' =>'1', 'name' => 'Huaracaje'],
    		['depa_id' =>'6', 'name' => 'Cobija'],
    		['depa_id' =>'6', 'name' => 'Porvenir'],
    		['depa_id' =>'6', 'name' => 'Bolpebra'],
    		['depa_id' =>'6', 'name' => 'Bella Flor'],
    		['depa_id' =>'6', 'name' => 'Puerto Rico'],
    		['depa_id' =>'6', 'name' => 'San Pedro'],
    		['depa_id' =>'6', 'name' => 'Filadelfia'],
    		['depa_id' =>'6', 'name' => 'Puerto Gonzalo Moreno'],
    		['depa_id' =>'6', 'name' => 'San Lorenzo'],
    		['depa_id' =>'6', 'name' => 'El Sena'],
    		['depa_id' =>'6', 'name' => 'Ingavi'],
    		['depa_id' =>'6', 'name' => 'Nueva Esperanza'],
    		['depa_id' =>'6', 'name' => 'Villa Nueva'],
    		['depa_id' =>'6', 'name' => 'Santos Mercado']

    	];
    	
    	foreach ($statuses as $status) {

                Muserpol\Municipios::create($status);
            
        }
    }
}
